config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "messages#index"
  resources :sessions
  resources :messages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :my_authenticate, only: [:show, :new, :edit, :create, :update, :destroy]
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def my_authenticate
    if session[:user_id].nil?
      redirect_to root_path
    end
  end

  # GET /messages
  # GET /messages.json
  def index
    if session[:user_id].nil?
      #redirect_to :controller => 'sessions', :action => 'new'
      #return
      render template: "sessions/new"
    else
      if session[:user_id] % 2 == 1
        her_id = session[:user_id]
        my_id = session[:user_id] + 1
      else
        her_id = session[:user_id] - 1
        my_id = session[:user_id]
      end
      @messages = Message.where(userid: her_id).or(Message.where(userid: my_id)).order('id DESC').page(params[:page]).per(10)
    end
    #respond_to do |format|

    #end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.userid = session[:user_id]

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        #format.mobile { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        #format.mobile { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if if @message.userid == session[:user_id]; @message.update(message_params) else false end
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        #format.mobile { redirect_to @message, notice: 'Message was successfully updated.' }
        #format.json { render :show, status: :ok, location: @message }
        format.json { head :no_content }
      else
        format.html { render :edit }
        #format.mobile { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy if @message.userid == session[:user_id]
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      #format.mobile { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
      if @message.userid != session[:user_id]
        @message = nil
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:userid, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:password] == "sakura"
      session[:user_id] = 1
      redirect_to :controller => 'messages', :action => 'index'
    elsif params[:password] == "uuusakura"
      session[:user_id] = 2
      redirect_to :controller => 'messages', :action => 'index'
    elsif params[:password] == "asunapppppp"
      session[:user_id] = 3
      redirect_to :controller => 'messages', :action => 'index'
    elsif params[:password] == "uuuasuna"
      session[:user_id] = 4
      redirect_to :controller => 'messages', :action => 'index'
    else
      #session[:user_id] = nil
      session.delete(:user_id)
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
      #session[:user_id] = nil
      session.delete(:user_id)
      #redirect_to :controller => 'messages', :action => 'index'
      redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Room</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/taka/">憩の部屋</a>

  <!--div class="collapse navbar-collapse" id="navbarSupportedContent"-->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/taka/">Home</a>
      </li>
      <li class="nav-item">
        <% if not session[:user_id].nil? %>
          <%= link_to 'ログアウト', session_path(1), class: "nav-link", :method => :delete %>
        <% end %>
      </li>
    </ul>
  <!--/div-->
</nav>
  
  <div class="container">
  
    <%= yield %>

  </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, html: {class: 'form-group'}) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :userid %>
  </div-->
  <div class="form-group">
       メッセージ<br>
    <%= f.text_area :body, class: "form-control form-control-lg" %>
  </div>
  <%= f.submit "書き込む", class: 'btn btn-primary' %>
<% end %>

app/views/messages/edit.html.erb
<div class="mt-3">
<h2>編集画面</h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mt-3">
<%= link_to 'メッセージを書く', new_message_path %>
</div>

<br />

<table>
  <tbody>
  <!--tr>
    <th>Userid</th>
    <th>Body</th>
    <th>日付</th>
    <th></th>
    <th></th>
    <th></th>
  </tr-->

<% @messages.each do |message| %>
  <tr>
    <!--td><%= message.userid %></td-->
    	<% case message.userid % 2
			when 1 then %>
	<td style="vertical-align: top; width: 5px">
   		<p><%= image_tag 'ineko3b.gif' %></p>
   	</td>
    <td style="vertical-align: top; color: #FF69B4">
		<%= simple_format(h(message.body)) %>
    </td>
    	<% when 0 then %>
	<td style="vertical-align: top">
   		<p><%= image_tag 'iuki1d.gif' %></p>
   	</td>
    <td style="vertical-align: top; color: blue">
    	<%= simple_format(h(message.body)) %>
    </td>
    	<% else %>
    	<td colspan="2">
    		error message.userid=<%= message.userid %>
    	</td>
    	<%	end %>
    <td style="vertical-align: top"><p><%= message.created_at.strftime("%Y年%m月%d日, %H:%M:%S") %></p></td>
    <!--td style="vertical-align: top"><p><%= link_to 'Show', message %></td-->
    <% if message.userid == session[:user_id] %>
    <td style="vertical-align: top" nowrap><p><%= link_to '編集', edit_message_path(message) %></p></td>
    <td style="vertical-align: top" nowrap><p><%= link_to '削除', message, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
    <% end %>
  </tr>
<% end %>
  </tbody>
</table>

<%= paginate(@messages) %>
<br />

app/views/messages/new.html.erb
<div class="mt-3">
<h2>書き込み画面</h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<!--p>
  <strong>Userid:</strong>
  <%= @message.userid %>
</p-->

<p>
  <strong>メッセージ:</strong>
  <%= simple_format(h(@message.body)) %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>